friends/friends/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include(('users.urls.urls', 'users'), namespace='users')),
    path('posts/', include(('posts.urls.urls', 'posts'), namespace='posts')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

friends/posts/urls/urls.py
from django.urls import path

from posts.views import PostCreateView, PostListView


urlpatterns = [
    path('list/<username>/', PostListView.as_view(), name='posts'),
    path('create/', PostCreateView.as_view(), name='create'),
]

friends/users/urls/urls.py
from django.urls import path

from users.views import (
    CreateUserView,
    LoginView,
    Profile,
    logout_view
)


urlpatterns = [
    path('signup/', CreateUserView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', Profile.as_view(), name='profile')
]

friends/posts/models.py
from django.db import models


class Post(models.Model):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE)
    text = models.CharField(max_length=512)
    created = models.DateTimeField(auto_now_add=True)

friends/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from users.managers import UserManager


class User(AbstractUser):
    objects = UserManager()

friends/posts/forms.py
from django.forms import ModelForm

from posts.models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text']

friends/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class CreateUserForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            User.USERNAME_FIELD,
            User.get_email_field_name(),
            'password1',
            'password2'
        )


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=150
    )
    password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput()
    )

    class Meta:
        fields = ('username', 'password')

friends/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.urls import reverse

from posts.forms import PostForm
from posts.models import Post
from users.models import User


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(user__username=user.username)

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)

        username = self.kwargs.get('username')
        context['posts'] = Post.objects.filter(user__username=username)
        context['username'] = username
        return context


class PostCreateView(FormView):
    template_name = 'posts/post_create.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('posts:posts', kwargs={'username': self.request.user.username})

friends/users/views.py
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import FormView

from users.forms import CreateUserForm, LoginForm


class CreateUserView(FormView):
    template_name = 'users/registration.html'
    form_class = CreateUserForm
    success_url = 'users/profile/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = 'users:profile'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        print("username", username)
        print("password", password)
        user = authenticate(self.request, username=username, password=password)
        print("user", user)
        if user:
            login(self.request, user)
            return HttpResponseRedirect(reverse(self.success_url))
        else:
            return self.get(self.request)


class Profile(TemplateView):
    template_name = 'users/profile.html'


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

friends/templates/base.html
{% load static %}
<html>
	<head>
	</head>
	<body>
		<div id="root">
		{% block content %}
		{% endblock %}
		</div>
		<!-- <script src="{% static 'build/bundle.js' %}"> -->
	</body>
</html>

friends/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
{% if form.errors %}
<h1>errors</h1>
{{ form.errors }}
{% endif %}

<form method="post" action="{% url 'posts:create' %}">
    {% csrf_token %}
    <div>
        <td>{{ form.text.label_tag }}</td>
		<td>{{ form.text }}</td>
    </div>
    <div>
        <input type="submit" value="post" />
		<input type="hidden" name="next" value="{{ next }}" />
    </div>
</form>

{% endblock %}

friends/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Posts by {{ username }}</h1>

{% for post in posts %}
<div>
    <span>{{ post.text }}</span>
    Created: {{ post.created }}
</div>
{% endfor %}

{% endblock %}

friends/templates/users/login.html
{% extends 'base.html' %}
{% block content %}

{% if form.errors %}
<div>
	<h1>errors</h1>
	{{ form.errors }}
</div>
{% endif %}

<form method="post" action="{% url 'users:login' %}">
	{% csrf_token %}
	<div>
		<td>{{ form.username.label_tag }}</td>
		<td>{{ form.username }}</td>
	</div>
	<div>
		<td>{{ form.password.label_tag }}</td>
		<td>{{ form.password }}</td>
	</div>
	<div>
		<input type="submit" value="login" />
		<input type="hidden" name="next" value="{{ next }}" />
	</div>
</form>
{% endblock %}

friends/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}

<h1>Profile</h1>
{{ user }}

{% endblock %}

friends/templates/users/registration.html
{% extends 'base.html' %}
{% block content %}

{% if form.errors %}
<div>
	{{ form.errors }}
</div>
{% endif %}

<form method="post" action="{% url 'users:signup' %}">
	{% csrf_token %}
	<div>
		<td>{{ form.username.label_tag }}</td>
		<td>{{ form.username }}</td>
	</div>
	<div>
		<td>{{ form.email.label_tag }}</td>
		<td>{{ form.email }}</td>
	</div>
	<div>
		<td>{{ form.password1.label_tag }}</td>
		<td>{{ form.password1 }}</td>
	</div>
	<div>
		<td>{{ form.password2.label_tag }}</td>
		<td>{{ form.password2 }}</td>
	</div>
	<div>
		<input type="submit" value="signup" />
		<input type="hidden" name="next" value="{{ next }}" />
	</div>
</form>
{% endblock %}